jobs:
  publish-npm:
    needs: testing
    secrets: inherit
    uses: Beuterei/reusable-workflows/.github/workflows/package-publish.yml@main
  testing:
    permissions:
      pull-requests: write
    secrets: inherit
    uses: Beuterei/reusable-workflows/.github/workflows/node-qa-tests.yml@main
    with:
      test_runner: vitest
name: "Publish pack with latest dist-tag with npm registry"

on:
  release:
    types:
      - created
